import { TextVariantPresets } from './typesText';
export const TEXT_VARIANT_PRESETS: TextVariantPresets = {
  displayPrimary: {
    size: '6xl',
    weight: 'bold',
    family: 'heading',
    lineHeight: 'tight',
    letterSpacing: 'tighter',
    color: 'primary',
  },
  displayAccent: {
    size: '6xl',
    weight: 'bold',
    family: 'heading',
    lineHeight: 'tight',
    letterSpacing: 'tighter',
    color: 'accent',
  },
  headingPrimary: {
    size: '4xl',
    weight: 'semibold',
    family: 'heading',
    lineHeight: 'tight',
    letterSpacing: 'tight',
    color: 'primary',
  },
  headingAccent: {
    size: '4xl',
    weight: 'semibold',
    family: 'heading',
    lineHeight: 'tight',
    letterSpacing: 'tight',
    color: 'accent',
  },
  titlePrimary: {
    size: '2xl',
    weight: 'semibold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'primary',
  },
  titleSecondary: {
    size: '2xl',
    weight: 'semibold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'secondary',
  },
  titleAccent: {
    size: 'lg',
    weight: 'bold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'accent',
  },
  titleAccentBold: {
    size: '2xl',
    weight: 'bold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'accent',
  },
  bodyPrimary: {
    size: 'md',
    weight: 'regular',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'primary',
  },
  bodySecondary: {
    size: 'md',
    weight: 'regular',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'secondary',
  },
  bodyBold: {
    size: 'md',
    weight: 'bold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'primary',
  },
  bodyBoldAccent: {
    size: 'md',
    weight: 'bold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'accent',
  },
  bodyMuted: {
    size: 'md',
    weight: 'regular',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'muted',
  },
  bodyError: {
    size: 'md',
    weight: 'regular',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'error',
  },
  bodySuccess: {
    size: 'md',
    weight: 'regular',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'success',
  },
  bodyAccent: {
    size: 'md',
    weight: 'semibold',
    family: 'body',
    lineHeight: 'comfortable',
    letterSpacing: 'normal',
    color: 'accent',
  },
  captionSecondary: {
    size: 'sm',
    weight: 'regular',
    family: 'body',
    lineHeight: 'relaxed',
    letterSpacing: 0.5,
    color: 'secondary',
  },
  captionMuted: {
    size: 'sm',
    weight: 'regular',
    family: 'body',
    lineHeight: 'relaxed',
    letterSpacing: 0.5,
    color: 'muted',
  },
  captionError: {
    size: 'sm',
    weight: 'regular',
    family: 'body',
    lineHeight: 'relaxed',
    letterSpacing: 0.5,
    color: 'error',
  },
  labelPrimary: {
    size: 'xs',
    weight: 'medium',
    family: 'ui',
    lineHeight: 'comfortable',
    letterSpacing: 0.5,
    color: 'primary',
  },
  labelSecondary: {
    size: 'xs',
    weight: 'medium',
    family: 'ui',
    lineHeight: 'comfortable',
    letterSpacing: 0.5,
    color: 'secondary',
  },
  labelError: {
    size: 'xs',
    weight: 'medium',
    family: 'ui',
    lineHeight: 'comfortable',
    letterSpacing: 0.5,
    color: 'error',
  },
};
