import { StyleSheet } from 'react-native';
import { ArenaColors, ArenaSpacing, ArenaTypography } from '@/constants';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ArenaColors.neutral.darkest,
    paddingHorizontal: ArenaSpacing['4xl'],
    paddingVertical: ArenaSpacing['6xl'],
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  logoContainer: {
    marginBottom: ArenaSpacing['5xl'],
    alignItems: 'center',
  },
  logo: {
    fontSize: ArenaTypography.size['6xl'],
    fontWeight: ArenaTypography.weight.extrabold,
    color: ArenaColors.brand.primary,
    letterSpacing: ArenaTypography.letterSpacing.wide,
    textAlign: 'center',
    marginBottom: ArenaSpacing.md,
  },
  tagline: {
    fontSize: ArenaTypography.size.lg,
    fontWeight: ArenaTypography.weight.regular,
    color: ArenaColors.neutral.light,
    textAlign: 'center',
    letterSpacing: ArenaTypography.letterSpacing.normal,
  },
  welcomeContainer: {
    marginBottom: ArenaSpacing['5xl'],
    alignItems: 'center',
  },
  welcomeTitle: {
    fontSize: ArenaTypography.size['4xl'],
    fontWeight: ArenaTypography.weight.bold,
    color: ArenaColors.neutral.light,
    textAlign: 'center',
    marginBottom: ArenaSpacing.lg,
    letterSpacing: ArenaTypography.letterSpacing.normal,
  },
  welcomeDescription: {
    fontSize: ArenaTypography.size.md,
    fontWeight: ArenaTypography.weight.regular,
    color: ArenaColors.neutral.medium,
    textAlign: 'center',
    lineHeight: ArenaTypography.lineHeight.relaxed * ArenaTypography.size.md,
    marginBottom: ArenaSpacing.xl,
    paddingHorizontal: ArenaSpacing.lg,
  },
  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: ArenaSpacing['2xl'],
    gap: ArenaSpacing.lg,
    paddingHorizontal: ArenaSpacing.xl,
  },
  buttonText: {
    fontSize: ArenaTypography.size.lg,
    fontWeight: ArenaTypography.weight.semibold,
    color: ArenaColors.neutral.light,
    letterSpacing: ArenaTypography.letterSpacing.wide,
  },
  buttonTextDisabled: {
    color: ArenaColors.disabled.text,
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: `${ArenaColors.neutral.darkest}CC`,
  },
  loadingText: {
    fontSize: ArenaTypography.size.md,
    fontWeight: ArenaTypography.weight.medium,
    color: ArenaColors.neutral.light,
    marginTop: ArenaSpacing.lg,
  },
  footer: {
    marginTop: 'auto',
    alignItems: 'center',
  },
  footerText: {
    fontSize: ArenaTypography.size.sm,
    fontWeight: ArenaTypography.weight.light,
    color: ArenaColors.neutral.medium,
    textAlign: 'center',
    opacity: 0.7,
  },
});
